<?php

/**
 * @OA\Info(
 *     title="Telecom API",
 *     version="1.2.0",
 *     description="Telecom API for managing users, wallets, airtime/data transactions, and third‑party provider integrations. Use the /api prefix for all endpoints (e.g. /api/products).",
 *     termsOfService="https://your-production-domain.com/terms",
 *     @OA\Contact(
 *         name="Ifeoluwa .Py",
 *         url="https://github.com/Ife-py",
 *         email="dev@telecomapi.local"
 *     ),
 *     @OA\License(
 *         name="MIT",
 *         url="https://opensource.org/licenses/MIT"
 *     )
 * )
 *
 * # Servers
 * @OA\Server(
 *     url="http://127.0.0.1:8000/api",
 *     description="Local development (php artisan serve)"
 * )
 * @OA\Server(
 *     url="http://localhost:8080/api",
 *     description="Local Docker (docker-compose)"
 * )
 * @OA\Server(
 *     url="https://api.your-production-domain.com",
 *     description="Production"
 * )
 *
 * # Security - Laravel Sanctum / Bearer tokens
 * @OA\SecurityScheme(
 *     securityScheme="BearerAuth",
 *     type="http",
 *     scheme="bearer",
 *     bearerFormat="JWT",
 *     description="Send a bearer token generated by the API (Laravel Sanctum personal access token or JWT). Example: 'Authorization: Bearer {token}'"
 * )
 *
 * # Common tags to group endpoints in the UI
 * @OA\Tag(name="Auth",           description="Authentication & registration endpoints")
 * @OA\Tag(name="Users",          description="User profile and management")
 * @OA\Tag(name="Wallets",        description="User wallets, balance and funding")
 * @OA\Tag(name="Transactions",   description="Airtime/data purchases and transaction history")
 * @OA\Tag(name="Providers",      description="Third-party telecom providers & integrations")
 * @OA\Tag(name="Products",       description="Products: airtime, bundles, plans")
 * @OA\Tag(name="Admin",          description="Administrative endpoints")
 *
 * @OA\ExternalDocumentation(
 *     description="API usage guide & examples",
 *     url="https://github.com/Ife-py/TelecomPlugApi/blob/main/README.md"
 * )
 */
